services:
  zipper:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "4199:4199"
    volumes:
      - ./data:/app/data
    networks:
      - zipper-net

networks:
  zipper-net:
    external: true
